export const GET_STACKOVERFLOW_INFO_REQUEST = 'GET_STACKOVERFLOW_INFO_REQUEST';
export const GET_STACKOVERFLOW_INFO_SUCCESS = 'GET_STACKOVERFLOW_INFO_SUCCESS';
export const GET_STACKOVERFLOW_INFO_FAIL = 'GET_STACKOVERFLOW_INFO_FAIL';